#!/bin/sh
### BEGIN INIT INFO
# Provides:          avahi-dnsconfd
# Required-Start:    $remote_fs avahi
# Required-Stop:     $remote_fs avahi
# Should-Start:	     $syslog
# Should-Stop:       $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Avahi mDNS/DNS-SD DNS configuration
# Description:       Zeroconf daemon for configuring your network 
#                    automatically
### END INIT INFO
#

# This file is part of avahi.
#
# avahi is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# avahi is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public
# License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with avahi; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
# USA.

#
# avahi-dnsconfd     avahi dns configuration daemon
#                               Daemon for ZeroConf
#
# Authors:      <sebastien.estienne@gmail.com>
#

#set -e

PATH=/sbin:/bin:/usr/sbin:/usr/bin
DESC="Avahi Unicast DNS Configuration Daemon"
NAME="avahi-dnsconfd"
DAEMON="/usr/sbin/$NAME"
SCRIPTNAME=/etc/init.d/$NAME

# Gracefully exit if the package has been removed.
test -x $DAEMON || exit 0

# don't start if /etc/default/avahi-dnsconfd says so.
AVAHI_DNSCONFD_START=1
test -f /etc/default/avahi-dnsconfd && . /etc/default/avahi-dnsconfd

if [ "$AVAHI_DNSCONFD_START" != "1" -a "$1" != "stop" ]; then
    exit 0
fi

#
#       Function that starts the daemon/service.
#
d_start() {
    $DAEMON -c
    [ $? = 0 ] && exit 0

    if [ -s /etc/localtime ]; then
        if [ ! -d /etc/avahi/etc ]; then
            mkdir -p /etc/avahi/etc >/dev/null 2>&1
        fi
        cp -fp /etc/localtime /etc/avahi/etc >/dev/null 2>&1
    fi;

    $DAEMON -D
}

#
#       Function that stops the daemon/service.
#
d_stop() {
    $DAEMON -c
    [ $? != 0 ] && exit 0

    $DAEMON -k
}

#
#       Function that reload the config file for the daemon/service.
#
d_refresh() {
    $DAEMON -c
    [ $? != 0 ] && exit 0

    $DAEMON -r
}

#
#       Function that check the status of the daemon/service.
#
d_status() {
    $DAEMON -c
    [ $? = 0 ]  && echo "$DESC is running" || echo "$DESC is not running"
}

case "$1" in
    start)
        d_start
        ;;
    stop)
        d_stop
        ;;
    refresh)
        d_refresh
        ;;
    reload|restart|force-reload)
        $DAEMON -c && d_stop
        d_start
        ;;
    status)
        d_status
        ;;
    *)
        echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload|reload}" >&2
        exit 1
        ;;
esac

exit 0
