#!/bin/sh
#
# SPDX-License-Identifier: GPL-2.0-only
#

### BEGIN INIT INFO
# Provides:          mpv-gui
# Required-Start:
# Required-Stop:
# Default-Start:     2
# Default-Stop:      0 6
# Short-Description: Launch MPV GUI
# Description:       Launch MPV GUI.
### END INIT INFO

. /etc/default/rcS
[ -f /etc/default/mpv-gui ] && . /etc/default/mpv-gui

case "$1" in
	start|"")
		printf '\e[3J' > /dev/tty0
		/usr/bin/mpv-gui $MPV_GUI_ROOT $MPV_GUI_DISPLAY1 $MPV_GUI_DISPLAY2 \
			$MPV_GUI_AUDIO_DEV1 $MPV_GUI_AUDIO_DEV2 $MPV_GUI_REMOTE1_MAC $MPV_GUI_REMOTE2_MAC & >/dev/null 2>&1
		;;
	stop)
		killall mpv-gui >/dev/null 2>&1
		;;
	*)
		echo "Usage: mpv-gui {start|stop}" >&2
		exit 1
		;;
esac

exit 0
